#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-couchdb
  labels:
    app: {{ .Release.Name }}-couchdb
spec:
  ports:
  - port: 5984
    name: couchdbport
  - port: 4369
    name: erlangport
  selector:
    app: {{ .Release.Name }}-ras