#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-couchdb-setup"
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    metadata:
      name: "{{ .Release.Name }}-couchdb-setup"
    spec:
      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
        {{- if .Values.nodeSelectors }}
{{ toYaml .Values.nodeSelectors | indent 8 }}
        {{- end }}
      restartPolicy: Never
      serviceAccountName: galasa
      initContainers:
      - name: wait-for-ras
        image: {{ .Values.kubectlImage }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command:
          - kubectl
        args:
          - wait
          - pods
          - -l=app={{ .Release.Name }}-ras
          - --for=condition=Ready
          - --timeout=90s
      containers:
      - name: create-couchdb-users-database
        image: {{ .Values.galasaRegistry }}/{{ .Values.galasaBootImage }}:{{ .Values.galasaVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command:
          - /bin/bash
          - -ec
          - |
            curl --silent --show-error -X PUT -H "Authorization: Basic ${GALASA_RAS_TOKEN}" http://{{ .Release.Name }}-couchdb:5984/_users
        env:
        - name: GALASA_RAS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-couchdb-secret
              key: GALASA_RAS_TOKEN