#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-custom-resource-monitor
  labels:
    galasa-monitor: custom
    app: {{ .Release.Name }}-custom-resource-monitor
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-custom-resource-monitor
  template:
    metadata:
      name: {{ .Release.Name }}-custom-resource-monitor
      labels:
        app: {{ .Release.Name }}-custom-resource-monitor
    spec:
      serviceAccountName: galasa
      nodeSelector:
        kubernetes.io/arch: {{ .Values.architecture }}
        {{- if .Values.nodeSelectors }}
{{ toYaml .Values.nodeSelectors | indent 8 }}
        {{- end }}
      containers:
      - name: resource-monitor
        image: {{ .Values.galasaRegistry }}/{{ .Values.galasaBootImage }}:{{ .Values.galasaVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ## 
        ## Provide some guidance to kubernetes on how much memory/cpu this container needs.
        {{- if .Values.cleanupMonitor }}
        {{- if .Values.cleanupMonitor.resources }}
        {{- with .Values.cleanupMonitor.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- end }}
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --resourcemanagement
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GALASA_EXTRA_BUNDLES
          value: {{ include "framework.extra.bundles" . }}
        - name: GALASA_CONFIG_STORE
          value: etcd:{{ include "cps.url" . }}
        - name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:{{ include "dss.url" . }}
        - name: GALASA_RESULTARCHIVE_STORE
          value: couchdb:http://{{ .Release.Name }}-couchdb:5984
        - name: GALASA_CREDENTIALS_STORE
          value: etcd:{{ include "creds.url" . }}
        - name: GALASA_RAS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-couchdb-secret
              key: GALASA_RAS_TOKEN
        {{- if .Values.cleanupMonitor.stream }}
        - name: GALASA_MONITOR_STREAM
          value: "{{ .Values.cleanupMonitor.stream }}"
        {{- end }}
        - name: GALASA_MONITOR_INCLUDES_GLOB_PATTERNS
          value: "{{ join "," .Values.cleanupMonitor.includes }}"
        - name: GALASA_MONITOR_EXCLUDES_GLOB_PATTERNS
          value: "{{ join "," .Values.cleanupMonitor.excludes }}"
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        livenessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 5
          periodSeconds: 10
