#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dex
  labels:
    app: {{ .Release.Name }}-dex
spec:
  ports:
  - name: http
    port: 5556
  - name: grpc
    port: 5557
  - name: telemetry
    port: 5558
  selector:
    app: {{ .Release.Name }}-dex