#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dex
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | indent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.externalHostname }}
    http:
      paths:
      - path: /dex(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-dex
            port:
              number: 5556
{{- end }}