#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
{{- if not .Values.encryption.keysSecretName }}
{{- $encryptionSecretName := (include "ecosystem.encryption.keys.secret.name" .)}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $encryptionSecretName) }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $encryptionSecretName }}
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
stringData:
  encryption-keys.yaml: |-
    encryptionKey: {{ randAlphaNum 32 | b64enc }}
    fallbackDecryptionKeys: []
{{- end }}
{{- end }}