#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd-external
  labels:
    app: {{ .Release.Name }}-etcd-external
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-etcd
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: client