#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
# eventStreamsSecretName set in values.yaml so use that Secret name for the lookup
{{- if .Values.eventStreamsSecretName }}

{{- $token := randAlphaNum 44 }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.eventStreamsSecretName) }}

# If a secret already exists, use the secret's existing token value
{{- if $existingSecret }}
{{- $token = printf (index $existingSecret.data "GALASA_EVENT_STREAMS_TOKEN") | b64dec }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ (printf "%s-%s" .Release.Name .Values.eventStreamsSecretName) }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end }}
