#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
# eventStreamsSecretName set in values.yaml so use that Secret name for the lookup
{{- if .Values.eventStreamsSecretName }}

{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.eventStreamsSecretName) }}

# The Secret name was set in values but the Secret does not exist
{{- if not $existingSecret }}

# The Secret must be called this to match the API/Engine Controller deployment spec
{{- $eventStreamsSecretName := "event-streams-token" }}
{{- $token := randAlphaNum 44 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $eventStreamsSecretName }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end -}}

# eventStreamsSecretName not set in values.yaml so generate a name and a Secret
{{- else }}

# The Secret must be called this to match the API/Engine Controller deployment spec
{{- $eventStreamsSecretName := "event-streams-token" }}
{{- $token := randAlphaNum 44 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $eventStreamsSecretName }}
type: Opaque
stringData:
  GALASA_EVENT_STREAMS_TOKEN: "{{ $token }}"

{{- end }}