#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics-external
  labels:
    app: {{ .Release.Name }}-metrics-external
spec:
  ports:
  - port: 9010
    name: metrics
  - port: 9011
    name: health
  selector:
    app: {{ .Release.Name }}-metrics