#
# Copyright contributors to the Galasa project
#
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-webui
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.externalHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-webui
            port:
              number: 8080
{{- end }}