#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v2
name: selenium-grid
description: A Helm chart for deploying a Selenium Grid with Firefox or Chrome Node(s)
type: application
home: "galasa.dev"
version: "0.1.0"
appVersion: "4.21.0"
