#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

{{- if and (and .Values.gatewayApi.enabled (not .Values.ingress.enabled)) (not .Values.gatewayApi.gatewayName) }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  {{- with .Values.gatewayApi.gatewayAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gatewayApi.gatewayClassName }}
  listeners:
  - hostname: {{ .Values.externalHostname }}
    name: {{ .Release.Name }}-http
    port: 80
    protocol: HTTP
  {{- if eq (include "ecosystem.host.scheme" .) "https" }}
  - hostname: {{ .Values.externalHostname }}
    name: {{ .Release.Name }}-https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      {{- with .Values.gatewayApi.tls.certificateRefs }}
      certificateRefs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
